environments:
  development:
    url: http://dev.bar.com
    name: Developer Setup
  production:
    url: http://foo.bar.com
    name: My Cool App

myconfig:
    app-name: My Application Name
    app-description: ${myconfig.app-name} is a Spring Boot Application
    admin-first-name: Naga
    admin-last-name: Kongara
    adminEmail: nagunix@gmail.com